export {default as Menu} from './Menu/Menu'
export {default as Home} from './Home/Home'
export {default as ImageSlider} from './ImageSlider/ImageSlider'
export {default as Courses} from './Courses/Courses'
export {default as About} from './About/About'
export {default as Placements} from './Placements/Placements'