export {default as SideMenu} from "../AdminDashboard/SideMenu/SideMenu"
export {default as Header} from "../AdminDashboard/Header/Header"
export {default as Footer} from "../AdminDashboard/Footer/Footer"
export {default as ViewAttendence} from "../AdminDashboard/Attendence/ViewAttendence"
export {default as CreateAttendence} from "../AdminDashboard/Attendence/CreateAttendence"
export {default as ViewPayment} from "../AdminDashboard/Payment/ViewPayment"
export {default as CreatePayment} from "../AdminDashboard/Payment/CreatePayment"
export {default as Dashboard} from "../AdminDashboard/Dashboard/Dashboard"
export {default as ManageWeb} from "../AdminDashboard/Manage Web/ManageWeb"
export {default as RegisterStudent} from "../AdminDashboard/students/RegisterStudent"